# Generated by Django 5.0.1 on 2024-02-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='borrowing_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
