# Generated by Django 5.0.1 on 2024-02-01 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_borrowing_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='borrowing_date',
            new_name='date',
        ),
    ]
