# Generated by Django 5.0.1 on 2024-02-01 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_rename_borrowing_date_book_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrow',
            old_name='borrowed_book',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='borrow',
            old_name='borrower',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='return',
            old_name='borrowed_book',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='return',
            old_name='borrower',
            new_name='user',
        ),
    ]
