# Generated by Django 5.0.1 on 2024-02-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_rename_borrowed_book_borrow_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_approved',
            field=models.BooleanField(default=False),
        ),
    ]
