# Generated by Django 5.0.1 on 2024-02-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_review_review_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='borrow_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_borrowing_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
